#!/bin/bash
#cd /media-ec2/ec2a/bufs_users/$1
su $1 -c "tar -C /media-ec2/ec2a/bufs_users/$1 -xvzf /media-ec2/ec2a/bufs_users/dropbox_install_files/dropbox-lnx.x86-0.7.110.tar.gz"
#su $1 -c "mkdir /media-ec2/ec2a/bufs_users/$1/Dropbox"
#su $1 -c "cp -R  /media-ec2/ec2a/bufs_users/$1  /media-ec2/ec2a/bufs_users/$1/Dropbox/$1_data/"

