#!/bin/bash
useradd $1 -b /media-ec2/ec2a/bufs_users -m -g 1003 -p `openssl passwd -crypt $2`
chmod 775 /media-ec2/ec2a/bufs_users/$1
rm -rf /media-ec2/ec2a/bufs_users/$1/*
# adduser --disabled-login --conf ./bufsuser.conf $1 
